[tool.poetry]
name = "apolo_11"
version = "0.1.0"
description = ""
authors = ["Juan Vargas <vargasjuan91@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pendulum = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
